---
- name: install proxychains4
  hosts: vds
  become: yes
  gather_facts: no
  vars:
    package_names:
      - gcc
      - make
      - proxychains4
  tasks:
    - name: Check if listed package is installed
      ansible.builtin.package_facts:
        manager: auto
      loop: "{{ package_names }}"

    - name: Install package if not installed
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names }}"
      when: not is_installed

    - name: check microsocks dir
      stat: path=~/microsocks/
      register: path

    - name: download repo from git
      ansible.builtin.git:
        repo: 'https://github.com/rofl0r/microsocks.git'
        dest: ~/microsocks
      when: not path.stat.exists